change:
  - head-branch: ['^change/']

enhancement:
  - head-branch: ['^feature/', '^feat/', '^enhancement/', '^enh/']

bug:
  - head-branch: ['^fix/', '^bug/']

chore:
  - head-branch: ['^chore/']

tests:
  - head-branch: ['^tests/', '^test/']
  - changed-files:
      - any-glob-to-any-file: ['__tests__/**/*']

documentation:
  - head-branch: ['^docs/', '^doc/']
  - changed-files:
      - any-glob-to-any-file: '**/*.md'

dependencies:
  - head-branch: ['^deps/', '^dep/', '^dependabot/', '^renovate/']
  - changed-files:
      - any-glob-to-any-file: ['package.json', 'yarn.lock']
