name: "Docker Image Update Checker"
description: "GitHub Action to check if the base Docker image that your image is based on was updated and your image needs to be updated"
author: Luca Comellini <lucacome>

inputs:
  base-image:
    description: "Docker base image"
    required: true
  image:
    description: "Docker image"
    required: true
  platforms:
    description: "Platforms to check"
    required: false
    default: "all"
outputs:
  needs-updating:
    description: "Whether the image needs updating"
  diff-images:
    description: "The diff of the images"

runs:
  using: node20
  main: "dist/index.js"

branding:
  icon: anchor
  color: blue
